import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'

export type Locale = 'zh-CN' | 'en-US'
export type ThemeMode = 'light' | 'dark'

const LOCALE_STORAGE_KEY = 'wyckoff.locale'
const THEME_STORAGE_KEY = 'wyckoff.theme'

const ZH = {
  'app.subtitle': '智能投研助手',
  'nav.chat': '读盘室',
  'nav.analysis': '单股分析',
  'nav.battle': '多股对抗',
  'nav.portfolio': '持仓诊断',
  'nav.history': '分析历史',
  'nav.tracking': '跟踪',
  'nav.attribution': '归因',
  'nav.export': '数据导出',
  'nav.membership': '星球会员',
  'nav.settings': '设置',
  'nav.group.core': '投研终端',
  'nav.group.data': '数据历史',
  'nav.group.models': '跟踪归因',
  'nav.group.system': '辅助系统',
  'external.home': '项目主页',
  'external.github': 'GitHub',
  'action.logout': '退出',
  'action.refresh': '刷新',
  'action.save': '保存',
  'action.cancel': '取消',
  'action.delete': '删除',
  'prefs.theme': '主题',
  'prefs.language': '语言',
  'prefs.light': '浅色',
  'prefs.dark': '深色',
  'prefs.switchToEnglish': 'Switch to English',
  'prefs.switchToChinese': '切换到中文',
  'common.loading': '加载中...',
  'common.empty': '暂无数据',
  'common.code': '代码',
  'common.name': '名称',
  'common.date': '日期',
  'common.stockCode': '股票/ETF代码',
  'common.exampleCode': 'A股/ETF: 601318 · 美股: AAPL · 港股: 00700',
  'common.configureFirst': '请先在设置页配置',
  'common.invalidStockCode': '请输入有效代码（A股/ETF 6位数字，美股英文代码，港股5位数字）',
  'common.marketHint': '支持 A 股、ETF、美股、港股 · 美股港股需',
  'common.tickflowLink': '购买 TickFlow 数据源',
  'common.rows': '条',
  'common.stocks': '支',
  'history.single': '单股分析历史',
  'history.battle': '多股对抗历史',
  'history.portfolio': '持仓诊断历史',
  'history.items': '条',
  'history.localOnly': '仅保存在当前浏览器，不写入数据库。',
  'history.empty': '暂无本地历史',
  'history.clear': '清空',
  'history.clearConfirm': '确认清空当前页面的本地历史？',
  'history.delete': '删除',
  'login.email': '邮箱',
  'login.password': '密码',
  'login.submit': '登录',
  'login.register': '注册',
  'login.processing': '处理中...',
  'login.hasAccount': '已有账号？',
  'login.noAccount': '没有账号？',
  'login.operationFailed': '操作失败',
  'login.rememberAccount': '记住账号',
  'login.passwordManagerHint': '密码由浏览器或系统密码管理器安全保存',
  'settings.title': '设置',
  'settings.account': '账号信息',
  'settings.saved': '已保存',
  'settings.saveFailed': '保存失败: {message}',
  'settings.saving': '保存中...',
  'settings.saveConfig': '保存配置',
  'settings.dataSources': '数据源',
  'settings.tickflowPromo': 'TickFlow 行情数据源（支持项目）',
  'settings.purchaseLink': '购买链接',
  'settings.tickflowApiKey': 'TickFlow API Key',
  'settings.capabilityCenter': '配置能力覆盖',
  'settings.capabilitySummary': '已配置 {ready}/{total} 项关键配置',
  'settings.testModel': '测试模型连通性',
  'settings.testModelHint': '会向当前模型发送一条极短测试请求，用来确认 API Key、模型名和 Base URL 是否可用；该请求会消耗模型额度，可能产生费用。',
  'settings.testModelConfirm': '将向当前模型发送一条极短测试请求，会消耗模型额度并可能产生费用。确认继续？',
  'settings.testModelMissing': '请先配置当前模型供应商的 API Key 和模型名称。',
  'settings.testDataSource': '测试数据源连通性',
  'settings.testDataSourceHint': '会使用 TickFlow Key 读取一条日线样例，确认数据源权限和网络可用性。',
  'settings.testDataSourceConfirm': '将使用 TickFlow Key 读取一条日线样例。确认继续？',
  'settings.testDataSourceMissing': '请先配置 TickFlow API Key。',
  'settings.testLoginRequired': '请先登录后再测试配置。',
  'settings.testFailed': '连通性测试失败',
  'settings.testSuccess': '连通性测试通过',
  'settings.testing': '测试中...',
  'settings.capabilityReady': '已保存',
  'settings.capabilityUnsaved': '未保存',
  'settings.capabilityMissingConfig': '缺少配置',
  'settings.capabilityUnsavedHint': '表单已填写，但尚未保存；读盘室只认已保存的配置。',
  'settings.capabilityCategoryData': '行情数据源',
  'settings.capabilityCategoryModel': '读盘室模型',
  'settings.marketCn': 'A 股/ETF',
  'settings.marketUs': '美股',
  'settings.marketHk': '港股',
  'settings.capabilityDailyKline': '日线 K 线',
  'settings.capabilityFundamentals': '基本面快照',
  'settings.capabilityExport': '数据导出',
  'settings.capabilityCrossMarket': '跨市场代码',
  'settings.capabilityReadingRoom': '模型问答',
  'settings.capabilityAiReport': 'AI 研报',
  'settings.capabilityStrategyReasoning': '策略推理',
  'settings.tickflowCapabilityNote': '单股图表、导出与跨市场读盘优先使用 TickFlow。',
  'settings.modelCapabilityNote': '读盘室、多股对抗、持仓诊断等 AI 分析使用当前模型配置。',
  'settings.modelConfig': '模型配置',
  'settings.oneRoutePromo': '1Route 模型中转（支持项目）',
  'settings.provider': '读盘室供应商',
  'settings.oneRouteNoAccount': '还没有 1Route 账号？',
  'settings.oneRouteInvite': '通过购买链接开通',
  'settings.apiKey': 'API Key',
  'settings.model': '模型',
  'settings.baseUrl': 'Base URL',
  'settings.notifications': '通知推送',
  'settings.feishuWebhook': '飞书 Webhook',
  'settings.wecomWebhook': '企业微信 Webhook',
  'settings.dingtalkWebhook': '钉钉 Webhook',
  'analysis.title': '单股分析',
  'analysis.missingTitle': '开始分析前还差一步配置',
  'analysis.missingModel': '请先配置读盘室模型的 API Key 和模型名称',
  'analysis.missingDataSource': '请先配置 TickFlow 股票数据源 API Key',
  'analysis.goSettings': '前往设置页',
  'analysis.modelRequirement': '读盘室模型 API Key / 模型',
  'analysis.dataRequirement': 'TickFlow 股票数据源 API Key',
  'analysis.missingPrefix': '请先在设置页完成配置：{items}',
  'analysis.configError': '配置状态异常，请前往设置页检查后重试',
  'analysis.exampleCode': 'A股/ETF: 601318 · 美股: AAPL.US · 港股: 00700.HK',
  'analysis.searchPlaceholder': '输入股票名称或代码，例如 中国平安 / AAPL / 腾讯',
  'analysis.searching': '搜索中...',
  'analysis.noSearchResults': '未找到匹配标的',
  'analysis.invalidStockCode': '请输入有效代码：A股/ETF 6位数字；美股/港股用 TickFlow 标准代码，例如 AAPL.US / 00700.HK',
  'analysis.marketHint': 'A 股/ETF 可填 6 位代码；美股/港股请填 TickFlow 标准代码（AAPL.US / 00700.HK），并需',
  'analysis.noKlineData': '没有获取到有效日线数据，请检查股票代码、TickFlow Key 或稍后重试。',
  'analysis.failed': '分析失败',
  'analysis.analyzing': '分析中...',
  'analysis.progressResolve': '解析代码...',
  'analysis.progressKline': '拉取 K 线...',
  'analysis.progressLLM': '模型分析中...',
  'analysis.start': '开始分析',
  'analysis.reportTitle': '威科夫大师研报',
  'analysis.chartTitle': '近 320 交易日结构图',
  'analysis.chartSubtitle': 'K 线、均线、支撑/压力与威科夫结构标记均来自 TickFlow 日线数据；新闻打点是读盘叠加层，不改变漏斗',
  'analysis.newsTitle': '关键新闻打点',
  'analysis.newsSubtitle': '只保留公告/业绩/股权/监管等可对齐到交易日的事件，最多 8 条',
  'analysis.newsEmpty': '窗口内没有通过规则过滤的关键新闻',
  'analysis.newsUnavailable': '新闻叠加暂不可用',
  'analysis.valueTitle': '价值面快照',
  'analysis.valueSubtitle': '盈利质量、成长、杠杆与现金流',
  'analysis.valueNoSource': '暂无来源',
  'analysis.valueRoe': 'ROE',
  'analysis.valueProfitYoy': '净利润同比',
  'analysis.valueRevenueYoy': '营收同比',
  'analysis.valueGrossMargin': '毛利率',
  'analysis.valueDebtRatio': '资产负债率',
  'analysis.valueCashRevenue': '现金流/营收',
  'analysis.valueQuality': '质量',
  'analysis.valueRisk': '风险',
  'analysis.valuePeriod': '报告期',
  'analysis.valueNoSignals': '暂无明显信号',
  'analysis.valueDataReady': '数据完整',
  'analysis.valueDataLimited': '字段不足',
  'analysis.valueDataStale': '数据较旧',
  'analysis.valueDataAgeDays': '天',
  'analysis.valueUnsupported': '价值面快照先支持 A 股。',
  'analysis.valueMissingSource': '需要 TickFlow 或 Tushare 数据源后展示价值面。',
  'analysis.valueUnavailable': '暂无可用基本面数据。',
  'analysis.valueScoreStrong': '稳健',
  'analysis.valueScoreNeutral': '中性',
  'analysis.valueScoreWeak': '承压',
  'analysis.valueScoreSevere': '高危',
  'analysis.valueSignalRoeStrong': 'ROE 维持在较好水平',
  'analysis.valueSignalProfitGrowth': '净利润保持正增长',
  'analysis.valueSignalRevenueGrowth': '营收保持正增长',
  'analysis.valueSignalGrossMargin': '毛利率较高',
  'analysis.valueSignalLowDebt': '杠杆压力较低',
  'analysis.valueSignalCashHealthy': '经营现金流匹配收入',
  'analysis.valueRiskRoeLoss': 'ROE 为负，盈利能力承压',
  'analysis.valueRiskProfitDrop': '净利润同比下滑',
  'analysis.valueRiskRevenueDrop': '营收同比下滑',
  'analysis.valueRiskGrossMarginLow': '毛利率偏低',
  'analysis.valueRiskHighDebt': '资产负债率偏高',
  'analysis.valueRiskCashWeak': '经营现金流偏弱',
  'analysis.valueRiskProfitCashFlowDivergence': '净利润增长但经营现金流负',
  'analysis.valueRiskWeakCashEarnings': '利润现金含量偏弱',
  'analysis.emptyTitle': '输入股票代码，开始威科夫大师分析',
  'analysis.emptySubtitle': '配置 TickFlow Key 后可显示 K 线图',
  'chat.title': '读盘室',
  'chat.noApiKey': '未配置 API Key',
  'chat.newChat': '新对话',
  'chat.emptyTitle': '我是威科夫，只看供需和主力行为',
  'chat.tryAsk': '试试问我：',
  'chat.fullVersionPrefix': '网页版对话历史保存在当前浏览器；跨会话记忆和后台长任务仍由 CLI / Actions 承载',
  'chat.unlockFull': '解锁完整能力',
  'chat.generating': '生成回复中...',
  'chat.thinking': '思考中...',
  'chat.stop': '停止生成',
  'chat.stopped': '已停止生成',
  'chat.liveRun': '本轮执行',
  'chat.toolRunning': '执行中',
  'chat.toolDone': '完成',
  'chat.sandboxQueued': '等待执行器',
  'chat.sandboxRunning': '沙箱执行中',
  'chat.sandboxCompleted': '结果已就绪',
  'chat.sandboxFailed': '执行失败',
  'chat.sandboxCancelled': '已取消',
  'chat.sandboxQueuedHint': '任务已进入队列，正在等待隔离执行器领取。',
  'chat.sandboxRunningHint': '隔离环境正在运行；关闭页面不会中断已领取的任务。',
  'chat.sandboxCompletedHint': '已取得最终计算输出，可让模型基于这个结果继续解读。',
  'chat.sandboxFailedHint': '隔离计算未完成，请查看错误输出后决定是否重新提交。',
  'chat.sandboxCancelledHint': '任务在被执行器领取前已取消。',
  'chat.sandboxCancel': '取消任务',
  'chat.sandboxInterpret': '解读结果',
  'chat.sandboxExitCode': '退出码：{code}',
  'chat.sandboxUsage': '沙箱用量：CPU {cpu} ms · 网络 {network} B',
  'chat.toolGroupMarketData': '市场数据读取',
  'chat.toolGroupDataLookup': '数据读取',
  'chat.toolGroupPartial': '部分完成',
  'chat.toolPartialFailure': '部分数据读取超时，已用可用结果继续判断。',
  'chat.toolInterrupted': '已中断',
  'chat.toolInterruptedHint': '本轮工具调用未完成，已忽略未完成结果。',
  'chat.awaitingApproval': '等待确认',
  'chat.approve': '确认执行',
  'chat.deny': '取消',
  'chat.denied': '已取消',
  'chat.placeholder': '输入消息...',
  'chat.queued': '排队中 #{index}',
  'chat.queueCount': '待发送 {count} 条',
  'chat.queueMessage': '加入队列',
  'chat.clearQueue': '清空队列',
  'chat.queueFull': '队列最多保留 5 条，请等当前回复完成后再继续发送。',
  'chat.configureLLM': '请先在设置页配置 LLM API Key',
  'chat.configErrorBadge': '配置服务异常',
  'chat.configHttpError': '读盘室配置服务异常（HTTP {status}）。请检查 API 服务的 Supabase 环境变量。',
  'chat.configUnreachable': '读盘室配置服务不可达，请确认 API 服务已启动，或检查 VITE_API_URL / CORS 配置。',
  'chat.requestFailed': '请求失败',
  'chat.toolCalls': '{count} 个工具调用',
  'chat.reasoningSteps': '{count} 个推理步骤',
  'chat.prompt.portfolio': '我有什么持仓',
  'chat.prompt.market': '大盘怎么样',
  'chat.prompt.recent': '最近复盘记录',
  'chat.prompt.search': '帮我搜一下宁德时代',
  'chat.prompt.screen': '帮我选股',
  'chat.prompt.strategy': '给个操作建议',
  'tool.search_stock': '搜索股票',
  'tool.view_portfolio': '查看持仓',
  'tool.market_overview': '大盘水温',
  'tool.market_history': '大盘回看',
  'tool.query_recommendations': '威科夫形态复盘',
  'tool.query_attribution': '策略归因',
  'tool.plan_portfolio_update': '调仓方案',
  'tool.execute_portfolio_update': '执行调仓',
  'tool.analyze_stock': '个股诊断',
  'tool.screen_stocks': '漏斗选股',
  'tool.generate_ai_report': 'AI 研报',
  'tool.generate_strategy_decision': '策略建议',
  'tool.intraday_analysis': '盘中分析',
  'tool.run_python_research': '隔离研究计算',
  'tool.web_search': '联网搜索',
  'portfolio.title': '持仓诊断',
  'portfolio.memberSubtitle': '星球会员可在此编辑并保存自己的云端持仓，再基于实时行情发起诊断。',
  'portfolio.manualSubtitle': '录入当前持仓后触发行情数据源和模型诊断；若数据源额度或并发受限，会提示升级入口。',
  'portfolio.dbMode': '数据库持仓',
  'portfolio.manualMode': '手动录入',
  'portfolio.missingModel': '请先在设置页配置读盘室模型 API Key 和模型名称',
  'portfolio.failed': '持仓诊断失败',
  'portfolio.invalidCode': '请输入有效代码：A股/ETF 6位数字；美股/港股用 TickFlow 标准代码，例如 AAPL.US / 00700.HK',
  'portfolio.totalAssets': '总资产（成本）',
  'portfolio.totalEquity': '最新总权益',
  'portfolio.freeCash': '可用资金',
  'portfolio.positionCount': '持仓数',
  'portfolio.positionCost': '持仓成本',
  'portfolio.empty': '暂无持仓，可通过 CLI 或读盘室 Agent 添加',
  'portfolio.emptyDb': '数据库里暂无持仓。可以先通过读盘室或 CLI 添加持仓后再回来诊断。',
  'portfolio.code': '股票代码',
  'portfolio.name': '股票名字',
  'portfolio.shares': '数量',
  'portfolio.costPrice': '成本价',
  'portfolio.buyDate': '建仓日',
  'portfolio.action': '操作',
  'portfolio.analyzeThis': '诊断',
  'portfolio.startDiagnosis': '开始诊断',
  'portfolio.dataHint': '诊断会读取近 320 根日线 K 线；数据源权限不足、并发或额度受限时会提示升级 TickFlow。',
  'portfolio.snapshot': '持仓快照',
  'portfolio.fullDiagnosis': '整体诊断',
  'portfolio.fullDiagnosisHint': '综合分析所有持仓+现金的资产配置',
  'portfolio.fullLoading': '正在分析全部持仓...',
  'portfolio.addPosition': '添加持仓',
  'portfolio.save': '保存到云端',
  'portfolio.saving': '正在保存...',
  'portfolio.saved': '持仓已保存到你的云端账户。',
  'portfolio.saveAndDiagnose': '保存并诊断',
  'battle.title': '多股对抗',
  'battle.subtitle': '输入任意数量股票，系统并发读取 TickFlow 日线，比较相对强弱并给出威科夫视角的胜负结论。',
  'battle.inputLabel': '股票代码或名称',
  'battle.inputHint': '支持换行、空格、逗号分隔；例如 中国平安、AAPL、00700.HK。输入数量不设上限。',
  'battle.start': '开始对抗',
  'battle.running': '对抗中...',
  'battle.missingModel': '请先在设置页配置读盘室模型 API Key 和模型名称',
  'battle.overlay': '重叠对比',
  'battle.separate': '分开展示',
  'battle.overlayLimit': '重叠数量',
  'battle.selectAll': '全选',
  'battle.clearAll': '反选清空',
  'battle.score': '强弱分',
  'battle.valueColumn': '价值面',
  'battle.valueTitle': '价值面对抗',
  'battle.valueSubtitle': 'A 股展示盈利质量、成长、杠杆与现金流；美股/港股暂不参与价值面评分。',
  'battle.drawdown': '回撤',
  'battle.report': '强弱结论',
  'tracking.title': '威科夫形态复盘',
  'tracking.description': '此页仅展示复盘表中最新 30 个复盘交易日的数据；这 30 个日期按数据库实际存在的入选日计算，不按连续自然日补齐。',
  'tracking.range': '当前保留范围：{oldest} 至 {latest}。',
  'tracking.window': '复盘交易日窗口',
  'tracking.windowOption': '近{size}个复盘交易日',
  'tracking.currentWindow': '当前窗口：{oldest} 至 {latest}，{count} 个复盘交易日，{rows} 条复盘记录',
  'tracking.coveredStocks': '覆盖股票数',
  'tracking.avgChange': '近{size}个复盘交易日覆盖股票平均累计涨幅',
  'tracking.bestChange': '最高涨幅',
  'tracking.worstChange': '最大跌幅',
  'tracking.totalRecommendations': '总入选次数',
  'tracking.winRate': '胜率',
  'tracking.avgWin': '平均盈利',
  'tracking.avgLoss': '平均亏损',
  'tracking.profitFactor': '盈亏比',
  'tracking.times': '次',
  'tracking.searchPlaceholder': '搜索代码或名称...',
  'tracking.onlyAI': '只看 AI 入选',
  'tracking.sortDate': '按日期',
  'tracking.sortChange': '按涨幅',
  'tracking.sortMfe': '按 MFE',
  'tracking.sortMae': '按 MAE',
  'tracking.sortScore': '按信号分',
  'tracking.sortRecommendCount': '按推荐次数',
  'tracking.sortDesc': '降序',
  'tracking.sortAsc': '升序',
  'tracking.recommendDate': '入选日',
  'tracking.recommendCount': '推荐次数',
  'tracking.initialPrice': '初始价',
  'tracking.currentPrice': '现价',
  'tracking.changePct': '涨跌幅',
  'tracking.score': '信号分',
  'tracking.scoreRaw': '形态',
  'tracking.scorePriority': '优先级',
  'tracking.pendingSignal': '待确认',
  'tracking.confirmedSignal': '已确认',
  'tracking.springboard': 'AI结构',
  'tracking.actionStatus': '状态',
  'tracking.mfePct': 'MFE',
  'tracking.maePct': 'MAE',
  'tracking.rangeAmpPct': '区间振幅',
  'tracking.empty': '暂无复盘记录',
  'tracking.tabCN': 'A股',
  'tracking.tabUS': '美股',
  'tracking.tabHK': '港股',
  'tracking.locked.eyebrow': '星球会员专属能力',
  'tracking.locked.title': '形态复盘跟踪暂未对当前账号开放',
  'tracking.locked.description': '这里沉淀每日全市场漏斗入选记录、最近 30 个复盘交易日表现、AI 入选标记、MFE/MAE 与信号分层统计。',
  'tracking.locked.window': '最近 30 个复盘交易日',
  'tracking.locked.windowDesc': '按数据库实际存在的入选日保留，不按连续自然日补齐。',
  'tracking.locked.signals': 'AI 入选与信号分层',
  'tracking.locked.signalsDesc': '查看推荐次数、信号分、AI 标记和不同市场表现。',
  'tracking.locked.replay': '复盘统计与回刷维护',
  'tracking.locked.replayDesc': 'MFE/MAE、平均涨幅窗口和后台补价回刷由共享系统维护。',
  'tracking.locked.ctaTitle': '加入知识星球开通星球会员',
  'tracking.locked.ctaDesc': '微信扫码加入后，请用当前登录邮箱联系星主开通。',
  'tracking.locked.qrAlt': '知识星球二维码',
  'tracking.locked.join': '查看加入方式',
  'tracking.locked.costLink': '查看成本模型',
  'tracking.locked.costNote': '费用用于共同平摊数据源、数据库、云服务器、AI API 和自动化任务等系统运维硬成本；不是投资顾问费，也不构成任何收益承诺。',
  'tracking.locked.memberHint': '已加入？请联系星主用当前登录邮箱绑定星球会员。',
  'export.title': '数据导出',
  'export.singleMode': '单标导出',
  'export.batchMode': '批量导出',
  'export.symbolPlaceholder': '华勤 / 601318 / AAPL.US / 00700.HK',
  'export.batchSymbols': '批量代码',
  'export.batchHint': '批量模式支持粘贴混合文本，自动提取并去重，单次最多 6 个标的。A股、ETF、指数可用 6 位代码或带 .SH/.SZ/.BJ 后缀，港股/美股使用 TickFlow 标准代码。',
  'export.days': '回溯天数',
  'export.endOffset': '结束偏移',
  'export.adjust': '复权',
  'export.qfq': '前复权',
  'export.hfq': '后复权',
  'export.noneAdjust': '不复权',
  'export.fetching': '获取中...',
  'export.fetch': '获取数据',
  'export.configureTickflow': '请先在设置页配置 TickFlow API Key',
  'export.apiError': 'TickFlow API 错误 ({status}): {message}',
  'export.noData': '未获取到有效数据，请检查股票代码或稍后重试',
  'export.failed': '导出失败',
  'export.failedStatus': '失败',
  'export.ok': '成功',
  'export.invalidSymbol': '请输入有效代码：A股/ETF/指数 6 位数字或 .SH/.SZ/.BJ 后缀，美股如 AAPL.US，港股如 00700.HK。',
  'export.batchEmpty': '请至少输入 1 个有效代码。',
  'export.batchTooMany': '批量导出单次最多 6 个标的，当前识别到 {count} 个。',
  'export.dataset': '数据集',
  'export.enhancedView': '增强 OHLCV',
  'export.rawView': '原始行情',
  'export.enhancedCsv': '增强 CSV',
  'export.rawCsv': '原始 CSV',
  'export.selectedCsv': '所选字段',
  'export.zip': '打包 ZIP',
  'export.columnFilter': '筛选字段',
  'export.selectAll': '全选',
  'export.selectedCount': '已选 {count} 列',
  'export.emptyTitle': '输入股票代码，导出历史行情 CSV',
  'export.emptySubtitle': '支持增强 OHLCV、原始行情、字段选择和批量打包',
  'guide.title': '星球会员',
  'guide.subtitle': '查看当前会员状态、专属能力，以及普通用户仍可使用的功能。',
  'guide.core': '核心功能',
  'guide.coreDesc': '从自然语言读盘，到图表分析、对抗比较、持仓诊断和浏览器本地历史。',
  'guide.modules': '工具与数据模块',
  'guide.module': '模块',
  'guide.description': '说明',
  'guide.rhythm': '日常节奏',
  'guide.configEntry': '配置入口',
  'guide.configDesc': '首次使用前在设置页配置 Supabase、LLM 模型与数据源；生产环境里，信号、持仓和个人设置按用户隔离，分析历史默认只保存在当前浏览器。',
  'guide.workflow.chat.title': '读盘室',
  'guide.workflow.chat.desc': '用自然语言串联行情查询、单股诊断、漏斗选股、持仓检查和调仓方案；适合快速追问和临场判断。',
  'guide.workflow.analysis.title': '单股分析',
  'guide.workflow.analysis.desc': '支持 A 股、ETF、美股、港股，展示 320 日日线结构、Wyckoff 标记、价值快照、AI 报告和本地历史。',
  'guide.workflow.battle.title': '多股对抗',
  'guide.workflow.battle.desc': '输入多个标的后比较相对强弱、回撤、量能和价值面，支持叠加图、分图和本地历史回看。',
  'guide.workflow.portfolio.title': '持仓诊断',
  'guide.workflow.portfolio.desc': '星球会员可视化编辑并保存自己的云端持仓后诊断，普通用户可手动临时录入；结果包含仓位、盈亏、价值风险和本地历史。',
  'guide.tool.market': '市场水温',
  'guide.tool.market.detail': '读取大盘、A50、VIX 与风险状态，作为所有判断的先验条件。',
  'guide.tool.tracking': '形态复盘',
  'guide.tool.tracking.detail': '星球会员可查看最近 30 个复盘交易日的入选记录、推荐次数、初始价、现价、MFE/MAE 和表现统计。',
  'guide.tool.signal': '信号池',
  'guide.tool.signal.detail': '汇总待确认、已确认、过期、拒绝等信号；生命周期维护和补价回刷由后台任务承载。',
  'guide.tool.export': '数据导出',
  'guide.tool.export.detail': '支持单标和最多 6 个标的批量导出，提供增强 OHLCV、原始行情、字段筛选和 ZIP 打包。',
  'guide.tool.history': '本地分析历史',
  'guide.tool.history.detail': '单股分析、多股对抗、持仓诊断结果保存在浏览器 IndexedDB，不写数据库，适合临时回看。',
  'guide.tool.model': '模型设置',
  'guide.tool.model.detail': '管理默认模型、备用模型、数据源 Key 和前端调用配置。',
  'guide.playbook.pre': '盘前',
  'guide.playbook.pre.text': '先看市场水温和候选池，确认当天风险温度，再决定哪些标的值得进入单股或对抗分析。',
  'guide.playbook.mid': '盘中',
  'guide.playbook.mid.text': '围绕重点股票做单股分析和多股对抗，用持仓与形态复盘校准风险暴露。',
  'guide.playbook.review': '复盘',
  'guide.playbook.review.text': '导出关键行情数据，回看浏览器本地历史和跟踪表现，形成下一次交易前的上下文。',
  'market.riskOn': '偏强',
  'market.bearRebound': '反抽',
  'market.neutral': '中性',
  'market.riskOff': '偏弱',
  'market.crash': '极弱',
  'market.blackSwan': '恶劣',
  'market.optimistic': '乐观',
  'market.cautiouslyOptimistic': '谨慎乐观',
  'market.cautious': '谨慎',
  'market.defensive': '保守',
  'market.mainIndex': '上证',
} as const

const EN: Record<keyof typeof ZH, string> = {
  'app.subtitle': 'Intelligent research assistant',
  'nav.chat': 'Reading Room',
  'nav.analysis': 'Stock Analysis',
  'nav.battle': 'Stock Battle',
  'nav.portfolio': 'Position Diagnosis',
  'nav.history': 'Analysis History',
  'nav.tracking': 'Tracking',
  'nav.attribution': 'Attribution',
  'nav.export': 'Data Export',
  'nav.membership': 'Planet Membership',
  'nav.settings': 'Settings',
  'nav.group.core': 'Research Terminal',
  'nav.group.data': 'Data & Logs',
  'nav.group.models': 'Quant Models',
  'nav.group.system': 'System Support',
  'external.home': 'Homepage',
  'external.github': 'GitHub',
  'action.logout': 'Log out',
  'action.refresh': 'Refresh',
  'action.save': 'Save',
  'action.cancel': 'Cancel',
  'action.delete': 'Delete',
  'prefs.theme': 'Theme',
  'prefs.language': 'Language',
  'prefs.light': 'Light',
  'prefs.dark': 'Dark',
  'prefs.switchToEnglish': 'Switch to English',
  'prefs.switchToChinese': '切换到中文',
  'common.loading': 'Loading...',
  'common.empty': 'No data',
  'common.code': 'Code',
  'common.name': 'Name',
  'common.date': 'Date',
  'common.stockCode': 'Stock / ETF code',
  'common.exampleCode': 'A-share/ETF: 601318 · US: AAPL · HK: 00700',
  'common.configureFirst': 'Please configure in Settings first',
  'common.invalidStockCode': 'Enter a valid code (A-share/ETF: 6 digits, US: ticker, HK: 5 digits)',
  'common.marketHint': 'Supports A-share, ETF, US & HK stocks · US/HK requires',
  'common.tickflowLink': 'TickFlow data source',
  'common.rows': 'rows',
  'common.stocks': 'stocks',
  'history.single': 'Stock analysis history',
  'history.battle': 'Stock battle history',
  'history.portfolio': 'Portfolio diagnosis history',
  'history.items': 'items',
  'history.localOnly': 'Stored only in this browser; not written to the database.',
  'history.empty': 'No local history yet',
  'history.clear': 'Clear',
  'history.clearConfirm': 'Clear local history for this page?',
  'history.delete': 'Delete',
  'login.email': 'Email',
  'login.password': 'Password',
  'login.submit': 'Sign in',
  'login.register': 'Sign up',
  'login.processing': 'Processing...',
  'login.hasAccount': 'Already have an account?',
  'login.noAccount': 'No account yet?',
  'login.operationFailed': 'Operation failed',
  'login.rememberAccount': 'Remember account',
  'login.passwordManagerHint': 'Password saving stays with your browser or system password manager',
  'settings.title': 'Settings',
  'settings.account': 'Account',
  'settings.saved': 'Saved',
  'settings.saveFailed': 'Save failed: {message}',
  'settings.saving': 'Saving...',
  'settings.saveConfig': 'Save settings',
  'settings.dataSources': 'Data sources',
  'settings.tickflowPromo': 'TickFlow market data source (supports this project)',
  'settings.purchaseLink': 'Purchase link',
  'settings.tickflowApiKey': 'TickFlow API Key',
  'settings.capabilityCenter': 'Configuration capability coverage',
  'settings.capabilitySummary': '{ready}/{total} key settings configured',
  'settings.testModel': 'Test model connection',
  'settings.testModelHint': 'Sends one tiny request to the selected model to verify the API key, model name, and Base URL. This consumes model quota and may cost money.',
  'settings.testModelConfirm': 'This will send one tiny request to the selected model, consuming quota and possibly costing money. Continue?',
  'settings.testModelMissing': 'Configure the current provider API key and model name first.',
  'settings.testDataSource': 'Test data source connection',
  'settings.testDataSourceHint': 'Uses your TickFlow key to fetch one daily-bar sample and verify data-source access.',
  'settings.testDataSourceConfirm': 'This will use your TickFlow key to fetch one daily-bar sample. Continue?',
  'settings.testDataSourceMissing': 'Configure TickFlow API Key first.',
  'settings.testLoginRequired': 'Sign in before testing settings.',
  'settings.testFailed': 'Connectivity test failed',
  'settings.testSuccess': 'Connectivity test passed',
  'settings.testing': 'Testing...',
  'settings.capabilityReady': 'Saved',
  'settings.capabilityUnsaved': 'Unsaved',
  'settings.capabilityMissingConfig': 'Missing config',
  'settings.capabilityUnsavedHint': 'Filled in the form but not saved yet. Reading Room only uses saved settings.',
  'settings.capabilityCategoryData': 'Market data source',
  'settings.capabilityCategoryModel': 'Reading Room model',
  'settings.marketCn': 'A-share/ETF',
  'settings.marketUs': 'US stocks',
  'settings.marketHk': 'HK stocks',
  'settings.capabilityDailyKline': 'Daily K-line',
  'settings.capabilityFundamentals': 'Fundamental snapshot',
  'settings.capabilityExport': 'Data export',
  'settings.capabilityCrossMarket': 'Cross-market symbols',
  'settings.capabilityReadingRoom': 'Model Q&A',
  'settings.capabilityAiReport': 'AI reports',
  'settings.capabilityStrategyReasoning': 'Strategy reasoning',
  'settings.tickflowCapabilityNote': 'Single-stock charts, exports, and cross-market reading prefer TickFlow.',
  'settings.modelCapabilityNote': 'Reading Room, stock battle, and portfolio diagnosis use the current model configuration.',
  'settings.modelConfig': 'Model configuration',
  'settings.oneRoutePromo': '1Route model gateway (supports this project)',
  'settings.provider': 'Reading Room provider',
  'settings.oneRouteNoAccount': 'No 1Route account yet?',
  'settings.oneRouteInvite': 'Open via purchase link',
  'settings.apiKey': 'API Key',
  'settings.model': 'Model',
  'settings.baseUrl': 'Base URL',
  'settings.notifications': 'Notifications',
  'settings.feishuWebhook': 'Feishu Webhook',
  'settings.wecomWebhook': 'WeCom Webhook',
  'settings.dingtalkWebhook': 'DingTalk Webhook',
  'analysis.title': 'Stock Analysis',
  'analysis.missingTitle': 'One more setup step before analysis',
  'analysis.missingModel': 'Configure the Reading Room model API Key and model name',
  'analysis.missingDataSource': 'Configure the TickFlow stock data API Key',
  'analysis.goSettings': 'Go to Settings',
  'analysis.modelRequirement': 'Reading Room model API Key / model',
  'analysis.dataRequirement': 'TickFlow stock data API Key',
  'analysis.missingPrefix': 'Please complete setup in Settings: {items}',
  'analysis.configError': 'Configuration looks inconsistent. Please check Settings and try again.',
  'analysis.exampleCode': 'A-share/ETF: 601318 · US: AAPL.US · HK: 00700.HK',
  'analysis.searchPlaceholder': 'Search by name or code, e.g. Ping An / AAPL / Tencent',
  'analysis.searching': 'Searching...',
  'analysis.noSearchResults': 'No matching symbol',
  'analysis.invalidStockCode': 'Enter a valid code: A-share/ETF 6 digits; US/HK TickFlow symbols such as AAPL.US / 00700.HK',
  'analysis.marketHint': 'A-share/ETF accepts 6 digits; US/HK must use TickFlow symbols (AAPL.US / 00700.HK) and requires ',
  'analysis.noKlineData': 'No valid daily K-line data was returned. Check the stock code, TickFlow Key, or try again later.',
  'analysis.failed': 'Analysis failed',
  'analysis.analyzing': 'Analyzing...',
  'analysis.progressResolve': 'Resolving code...',
  'analysis.progressKline': 'Fetching K-line...',
  'analysis.progressLLM': 'Model analyzing...',
  'analysis.start': 'Start analysis',
  'analysis.reportTitle': 'Wyckoff Research Report',
  'analysis.chartTitle': 'Last 320 Trading Days Structure',
  'analysis.chartSubtitle': 'Candles, moving averages, support/resistance, and Wyckoff markers are derived from TickFlow daily data. News pins are a chart-reading overlay, not a funnel gate.',
  'analysis.newsTitle': 'Key news pins',
  'analysis.newsSubtitle': 'Keeps filings, earnings, holdings, and regulatory events aligned to trading days, up to 8 items',
  'analysis.newsEmpty': 'No rule-filtered news events in this window',
  'analysis.newsUnavailable': 'News overlay is temporarily unavailable',
  'analysis.valueTitle': 'Value Snapshot',
  'analysis.valueSubtitle': 'Profit quality, growth, leverage, and cash flow',
  'analysis.valueNoSource': 'No source',
  'analysis.valueRoe': 'ROE',
  'analysis.valueProfitYoy': 'Net Profit YoY',
  'analysis.valueRevenueYoy': 'Revenue YoY',
  'analysis.valueGrossMargin': 'Gross Margin',
  'analysis.valueDebtRatio': 'Debt Ratio',
  'analysis.valueCashRevenue': 'Cash Flow / Revenue',
  'analysis.valueQuality': 'Quality',
  'analysis.valueRisk': 'Risk',
  'analysis.valuePeriod': 'Period',
  'analysis.valueNoSignals': 'No clear signal',
  'analysis.valueDataReady': 'Data complete',
  'analysis.valueDataLimited': 'Limited fields',
  'analysis.valueDataStale': 'Data is stale',
  'analysis.valueDataAgeDays': ' days',
  'analysis.valueUnsupported': 'Value snapshot currently supports A-shares first.',
  'analysis.valueMissingSource': 'Configure TickFlow or Tushare to show value data.',
  'analysis.valueUnavailable': 'No fundamental data available.',
  'analysis.valueScoreStrong': 'Solid',
  'analysis.valueScoreNeutral': 'Neutral',
  'analysis.valueScoreWeak': 'Pressured',
  'analysis.valueScoreSevere': 'Severe risk',
  'analysis.valueSignalRoeStrong': 'ROE remains at a healthy level',
  'analysis.valueSignalProfitGrowth': 'Net profit is growing',
  'analysis.valueSignalRevenueGrowth': 'Revenue is growing',
  'analysis.valueSignalGrossMargin': 'Gross margin is high',
  'analysis.valueSignalLowDebt': 'Leverage pressure is low',
  'analysis.valueSignalCashHealthy': 'Operating cash flow matches revenue',
  'analysis.valueRiskRoeLoss': 'ROE is negative',
  'analysis.valueRiskProfitDrop': 'Net profit is declining YoY',
  'analysis.valueRiskRevenueDrop': 'Revenue is declining YoY',
  'analysis.valueRiskGrossMarginLow': 'Gross margin is low',
  'analysis.valueRiskHighDebt': 'Debt ratio is elevated',
  'analysis.valueRiskCashWeak': 'Operating cash flow is weak',
  'analysis.valueRiskProfitCashFlowDivergence': 'Profit grows but operating cash flow is negative',
  'analysis.valueRiskWeakCashEarnings': 'Weak cash content of profit',
  'analysis.emptyTitle': 'Enter a stock code to start Wyckoff analysis',
  'analysis.emptySubtitle': 'Configure TickFlow Key to display K-line charts',
  'chat.title': 'Reading Room',
  'chat.noApiKey': 'API Key not configured',
  'chat.newChat': 'New chat',
  'chat.emptyTitle': 'I read only supply, demand, and operator behavior',
  'chat.tryAsk': 'Try asking:',
  'chat.fullVersionPrefix': 'Web chat history stays in this browser; cross-session memory and long background jobs still live in CLI / Actions',
  'chat.unlockFull': 'Unlock the full version',
  'chat.generating': 'Generating...',
  'chat.thinking': 'Thinking...',
  'chat.stop': 'Stop',
  'chat.stopped': 'Generation stopped',
  'chat.liveRun': 'Current run',
  'chat.toolRunning': 'Running',
  'chat.toolDone': 'Done',
  'chat.sandboxQueued': 'Waiting for worker',
  'chat.sandboxRunning': 'Sandbox running',
  'chat.sandboxCompleted': 'Result ready',
  'chat.sandboxFailed': 'Failed',
  'chat.sandboxCancelled': 'Cancelled',
  'chat.sandboxQueuedHint': 'The task is queued and waiting for the isolated worker.',
  'chat.sandboxRunningHint': 'The isolated environment is running. Closing this page will not interrupt a claimed task.',
  'chat.sandboxCompletedHint': 'The final output is ready. Ask the model to interpret this result.',
  'chat.sandboxFailedHint': 'The isolated calculation did not complete. Review the error output before resubmitting.',
  'chat.sandboxCancelledHint': 'The task was cancelled before the worker claimed it.',
  'chat.sandboxCancel': 'Cancel task',
  'chat.sandboxInterpret': 'Interpret result',
  'chat.sandboxExitCode': 'Exit code: {code}',
  'chat.sandboxUsage': 'Sandbox usage: CPU {cpu} ms · Network {network} B',
  'chat.toolGroupMarketData': 'Market data',
  'chat.toolGroupDataLookup': 'Data lookup',
  'chat.toolGroupPartial': 'Partial',
  'chat.toolPartialFailure': 'Some data timed out; continuing with the available results.',
  'chat.toolInterrupted': 'Interrupted',
  'chat.toolInterruptedHint': 'This tool run did not finish; incomplete results were ignored.',
  'chat.awaitingApproval': 'Awaiting approval',
  'chat.approve': 'Approve',
  'chat.deny': 'Deny',
  'chat.denied': 'Denied',
  'chat.placeholder': 'Type a message...',
  'chat.queued': 'Queued #{index}',
  'chat.queueCount': '{count} queued',
  'chat.queueMessage': 'Queue message',
  'chat.clearQueue': 'Clear queue',
  'chat.queueFull': 'Queue can hold up to 5 messages. Please wait for the current reply to finish.',
  'chat.configureLLM': 'Please configure an LLM API Key in Settings first',
  'chat.configErrorBadge': 'Config service error',
  'chat.configHttpError': 'Reading Room config service failed (HTTP {status}). Check the API service Supabase environment variables.',
  'chat.configUnreachable': 'Reading Room config service is unreachable. Confirm the API service is running, or check VITE_API_URL / CORS.',
  'chat.requestFailed': 'Request failed',
  'chat.toolCalls': '{count} tool calls',
  'chat.reasoningSteps': '{count} reasoning steps',
  'chat.prompt.portfolio': 'What positions do I hold?',
  'chat.prompt.market': 'How is the market?',
  'chat.prompt.recent': 'Recent pattern review records?',
  'chat.prompt.search': 'Search CATL for me',
  'chat.prompt.screen': 'Screen stocks for me',
  'chat.prompt.strategy': 'Give me an action plan',
  'tool.search_stock': 'Search stocks',
  'tool.view_portfolio': 'View portfolio',
  'tool.market_overview': 'Market temperature',
  'tool.market_history': 'Market history',
  'tool.query_recommendations': 'Wyckoff Pattern Review',
  'tool.query_attribution': 'Strategy attribution',
  'tool.plan_portfolio_update': 'Portfolio plan',
  'tool.execute_portfolio_update': 'Execute portfolio update',
  'tool.analyze_stock': 'Stock diagnosis',
  'tool.screen_stocks': 'Funnel screener',
  'tool.generate_ai_report': 'AI report',
  'tool.generate_strategy_decision': 'Strategy advice',
  'tool.intraday_analysis': 'Intraday analysis',
  'tool.run_python_research': 'Isolated research calculation',
  'tool.web_search': 'Web search',
  'portfolio.title': 'Position Diagnosis',
  'portfolio.memberSubtitle': 'Planet members can edit and save their own cloud positions, then diagnose them with live market data.',
  'portfolio.manualSubtitle': 'Enter a current position to trigger market-data and model diagnosis. Upgrade guidance appears when data-source quota or concurrency is limited.',
  'portfolio.dbMode': 'Database positions',
  'portfolio.manualMode': 'Manual entry',
  'portfolio.missingModel': 'Configure the Reading Room model API Key and model name first',
  'portfolio.failed': 'Position diagnosis failed',
  'portfolio.invalidCode': 'Enter a valid code: A-share/ETF 6 digits; US/HK TickFlow symbols such as AAPL.US / 00700.HK',
  'portfolio.totalAssets': 'Total assets (cost)',
  'portfolio.totalEquity': 'Latest total equity',
  'portfolio.freeCash': 'Available cash',
  'portfolio.positionCount': 'Positions',
  'portfolio.positionCost': 'Position cost',
  'portfolio.empty': 'No positions yet. Add them via CLI or the Reading Room Agent.',
  'portfolio.emptyDb': 'No database positions yet. Add positions via the Reading Room or CLI, then come back for diagnosis.',
  'portfolio.code': 'Stock code',
  'portfolio.name': 'Stock name',
  'portfolio.shares': 'Shares',
  'portfolio.costPrice': 'Cost price',
  'portfolio.buyDate': 'Entry date',
  'portfolio.action': 'Action',
  'portfolio.analyzeThis': 'Diagnose',
  'portfolio.startDiagnosis': 'Start diagnosis',
  'portfolio.dataHint': 'Diagnosis reads the latest 320 daily bars. TickFlow upgrade guidance appears when data-source access, quota, or concurrency is limited.',
  'portfolio.snapshot': 'Position snapshot',
  'portfolio.fullDiagnosis': 'Full diagnosis',
  'portfolio.fullDiagnosisHint': 'Analyze all positions + cash allocation',
  'portfolio.fullLoading': 'Analyzing all positions...',
  'portfolio.addPosition': 'Add position',
  'portfolio.save': 'Save to cloud',
  'portfolio.saving': 'Saving...',
  'portfolio.saved': 'Positions saved to your cloud account.',
  'portfolio.saveAndDiagnose': 'Save and diagnose',
  'battle.title': 'Stock Battle',
  'battle.subtitle': 'Enter any number of symbols. The app fetches TickFlow daily bars concurrently, compares relative strength, and returns a Wyckoff-style battle result.',
  'battle.inputLabel': 'Stock codes or names',
  'battle.inputHint': 'Separate entries by newline, space, or comma. Examples: Ping An, AAPL, 00700.HK. No input count limit.',
  'battle.start': 'Start battle',
  'battle.running': 'Battling...',
  'battle.missingModel': 'Configure the Reading Room model API Key and model name first',
  'battle.overlay': 'Overlay',
  'battle.separate': 'Separate charts',
  'battle.overlayLimit': 'Overlay count',
  'battle.selectAll': 'Select all',
  'battle.clearAll': 'Clear',
  'battle.score': 'Strength',
  'battle.valueColumn': 'Value',
  'battle.valueTitle': 'Value Battle',
  'battle.valueSubtitle': 'A-shares show profit quality, growth, leverage, and cash flow. US/HK symbols are not scored yet.',
  'battle.drawdown': 'Drawdown',
  'battle.report': 'Battle result',
  'tracking.title': 'Wyckoff Pattern Review',
  'tracking.description': 'This page shows data for the latest 30 review trading dates. Dates are based on records in the database, not continuous calendar days.',
  'tracking.range': 'Current retained range: {oldest} to {latest}.',
  'tracking.window': 'Review date window',
  'tracking.windowOption': 'Last {size} review dates',
  'tracking.currentWindow': 'Current window: {oldest} to {latest}, {count} review dates, {rows} records',
  'tracking.coveredStocks': 'Covered stocks',
  'tracking.avgChange': 'Avg cumulative change for stocks covered in the last {size} review dates',
  'tracking.bestChange': 'Best change',
  'tracking.worstChange': 'Worst change',
  'tracking.totalRecommendations': 'Total selections',
  'tracking.winRate': 'Win rate',
  'tracking.avgWin': 'Avg win',
  'tracking.avgLoss': 'Avg loss',
  'tracking.profitFactor': 'Profit factor',
  'tracking.times': 'times',
  'tracking.searchPlaceholder': 'Search code or name...',
  'tracking.onlyAI': 'AI selections only',
  'tracking.sortDate': 'Sort by date',
  'tracking.sortChange': 'Sort by change',
  'tracking.sortMfe': 'Sort by MFE',
  'tracking.sortMae': 'Sort by MAE',
  'tracking.sortScore': 'Sort by signal score',
  'tracking.sortRecommendCount': 'Sort by selections',
  'tracking.sortDesc': 'Descending',
  'tracking.sortAsc': 'Ascending',
  'tracking.recommendDate': 'Selection date',
  'tracking.recommendCount': 'Selections',
  'tracking.initialPrice': 'Initial price',
  'tracking.currentPrice': 'Current price',
  'tracking.changePct': 'Change',
  'tracking.score': 'Signal score',
  'tracking.scoreRaw': 'Pattern',
  'tracking.scorePriority': 'Priority',
  'tracking.pendingSignal': 'Pending',
  'tracking.confirmedSignal': 'Confirmed',
  'tracking.springboard': 'AI setup',
  'tracking.actionStatus': 'Status',
  'tracking.mfePct': 'MFE',
  'tracking.maePct': 'MAE',
  'tracking.rangeAmpPct': 'Range',
  'tracking.empty': 'No review records',
  'tracking.tabCN': 'A-Share',
  'tracking.tabUS': 'US',
  'tracking.tabHK': 'HK',
  'tracking.locked.eyebrow': 'Planet member benefit',
  'tracking.locked.title': 'Pattern review tracking is not enabled for this account',
  'tracking.locked.description': 'This page stores daily full-market funnel selections, latest 30 review trading dates, AI-selection marks, MFE/MAE, and signal-layer stats.',
  'tracking.locked.window': 'Latest 30 review trading dates',
  'tracking.locked.windowDesc': 'Retained by dates that actually exist in the database, not continuous calendar days.',
  'tracking.locked.signals': 'AI selections and signal layers',
  'tracking.locked.signalsDesc': 'Review selection counts, signal scores, AI marks, and performance across markets.',
  'tracking.locked.replay': 'Replay stats and repricing',
  'tracking.locked.replayDesc': 'MFE/MAE, average-change windows, and backend repricing are maintained by the shared system.',
  'tracking.locked.ctaTitle': 'Join Knowledge Planet to activate membership',
  'tracking.locked.ctaDesc': 'Scan the QR code in WeChat, then contact the owner with your current login email.',
  'tracking.locked.qrAlt': 'Knowledge Planet QR code',
  'tracking.locked.join': 'View access details',
  'tracking.locked.costLink': 'View cost model',
  'tracking.locked.costNote': 'The fee helps share operating costs for data feeds, databases, cloud servers, AI APIs, and scheduled automation. It is not an investment advisory fee and does not imply any return guarantee.',
  'tracking.locked.memberHint': 'Already joined? Contact the owner to bind membership to your current login email.',
  'export.title': 'Data Export',
  'export.singleMode': 'Single symbol',
  'export.batchMode': 'Batch export',
  'export.symbolPlaceholder': 'Huaqin / 601318 / AAPL.US / 00700.HK',
  'export.batchSymbols': 'Batch symbols',
  'export.batchHint': 'Batch mode accepts pasted mixed text, extracts and de-duplicates symbols, and supports up to 6 symbols per run. A-shares, ETFs, and indexes can use 6-digit codes or .SH/.SZ/.BJ suffixes; HK/US symbols use TickFlow format.',
  'export.days': 'Lookback days',
  'export.endOffset': 'End offset',
  'export.adjust': 'Adjustment',
  'export.qfq': 'Forward adjusted',
  'export.hfq': 'Backward adjusted',
  'export.noneAdjust': 'Unadjusted',
  'export.fetching': 'Fetching...',
  'export.fetch': 'Fetch data',
  'export.configureTickflow': 'Please configure TickFlow API Key in Settings first',
  'export.apiError': 'TickFlow API error ({status}): {message}',
  'export.noData': 'No valid data returned. Check the stock code or try again later.',
  'export.failed': 'Export failed',
  'export.failedStatus': 'Failed',
  'export.ok': 'OK',
  'export.invalidSymbol': 'Enter a valid code: 6-digit A-share/ETF/index code or .SH/.SZ/.BJ suffix, US like AAPL.US, HK like 00700.HK.',
  'export.batchEmpty': 'Enter at least 1 valid symbol.',
  'export.batchTooMany': 'Batch export supports at most 6 symbols per run; {count} were detected.',
  'export.dataset': 'Dataset',
  'export.enhancedView': 'Enhanced OHLCV',
  'export.rawView': 'Raw quotes',
  'export.enhancedCsv': 'Enhanced CSV',
  'export.rawCsv': 'Raw CSV',
  'export.selectedCsv': 'Selected fields',
  'export.zip': 'ZIP package',
  'export.columnFilter': 'Filter columns',
  'export.selectAll': 'Select all',
  'export.selectedCount': '{count} selected',
  'export.emptyTitle': 'Enter a stock code to export historical OHLCV CSV',
  'export.emptySubtitle': 'Enhanced OHLCV, raw quotes, field selection, and batch ZIP export',
  'guide.title': 'Planet Membership',
  'guide.subtitle': 'Check your membership status, member benefits, and capabilities that remain available to everyone.',
  'guide.core': 'Core features',
  'guide.coreDesc': 'From natural-language reading to chart analysis, stock battle, portfolio diagnosis, and browser-local history.',
  'guide.modules': 'Tools and data modules',
  'guide.module': 'Module',
  'guide.description': 'Description',
  'guide.rhythm': 'Daily rhythm',
  'guide.configEntry': 'Configuration',
  'guide.configDesc': 'Before first use, configure Supabase, LLM models, and data sources in Settings. Signals, portfolios, and personal settings are isolated by user; analysis history stays in the current browser by default.',
  'guide.workflow.chat.title': 'Reading Room',
  'guide.workflow.chat.desc': 'Connect market queries, stock diagnosis, funnel screening, portfolio checks, and rebalancing plans in natural language for fast follow-up questions.',
  'guide.workflow.analysis.title': 'Stock Analysis',
  'guide.workflow.analysis.desc': 'Supports A-share, ETF, US & HK stocks with a 320-day chart, Wyckoff markers, value snapshot, AI report, and local history.',
  'guide.workflow.battle.title': 'Stock Battle',
  'guide.workflow.battle.desc': 'Compare multiple symbols by relative strength, drawdown, volume, and value signals with overlay/separate charts and local history.',
  'guide.workflow.portfolio.title': 'Position Diagnosis',
  'guide.workflow.portfolio.desc': 'Planet members visually edit and save their own cloud positions before diagnosis; other users use temporary manual input. Results cover allocation, PnL, value risk, and local history.',
  'guide.tool.market': 'Market temperature',
  'guide.tool.market.detail': 'Reads broad market, A50, VIX, and risk regime as priors for every decision.',
  'guide.tool.tracking': 'Pattern review',
  'guide.tool.tracking.detail': 'Planet members can view the latest 30 review trading dates with selection count, initial/current price, MFE/MAE, and performance stats.',
  'guide.tool.signal': 'Signal pool',
  'guide.tool.signal.detail': 'Collects pending, survived, confirmed, expired, and rejected signals; lifecycle maintenance and repricing run in background jobs.',
  'guide.tool.export': 'Data export',
  'guide.tool.export.detail': 'Supports single-symbol and up to 6-symbol batch export with enhanced OHLCV, raw quotes, field filtering, and ZIP packaging.',
  'guide.tool.history': 'Local analysis history',
  'guide.tool.history.detail': 'Single-stock, stock battle, and portfolio diagnosis results are stored in browser IndexedDB, not the database, for temporary review.',
  'guide.tool.model': 'Model settings',
  'guide.tool.model.detail': 'Manages default models, fallback models, data-source keys, and frontend call configuration.',
  'guide.playbook.pre': 'Pre-market',
  'guide.playbook.pre.text': 'Check market temperature and candidates first, then decide which symbols deserve single-stock or battle analysis.',
  'guide.playbook.mid': 'Intraday',
  'guide.playbook.mid.text': 'Analyze key stocks and compare alternatives while using portfolio and pattern review to calibrate risk exposure.',
  'guide.playbook.review': 'Review',
  'guide.playbook.review.text': 'Export key market data, revisit browser-local history and tracking performance, then prepare context for the next session.',
  'market.riskOn': 'Risk-on',
  'market.bearRebound': 'Bear rebound',
  'market.neutral': 'Neutral',
  'market.riskOff': 'Risk-off',
  'market.crash': 'Very weak',
  'market.blackSwan': 'Severe',
  'market.optimistic': 'Optimistic',
  'market.cautiouslyOptimistic': 'Cautiously optimistic',
  'market.cautious': 'Cautious',
  'market.defensive': 'Defensive',
  'market.mainIndex': 'SSE',
}

export type TranslationKey = keyof typeof ZH

type TranslateVars = Record<string, string | number | null | undefined>

interface PreferencesContextValue {
  locale: Locale
  theme: ThemeMode
  setLocale: (locale: Locale) => void
  setTheme: (theme: ThemeMode) => void
  toggleTheme: () => void
  t: (key: TranslationKey, vars?: TranslateVars) => string
}

const PreferencesContext = createContext<PreferencesContextValue | null>(null)

export function PreferencesProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>(() => readLocale())
  const [theme, setThemeState] = useState<ThemeMode>(() => readTheme())

  useEffect(() => {
    document.documentElement.lang = locale
    window.localStorage.setItem(LOCALE_STORAGE_KEY, locale)
  }, [locale])

  useEffect(() => {
    document.documentElement.classList.toggle('dark', theme === 'dark')
    document.documentElement.style.colorScheme = theme
    window.localStorage.setItem(THEME_STORAGE_KEY, theme)
  }, [theme])

  const setLocale = useCallback((nextLocale: Locale) => setLocaleState(nextLocale), [])
  const setTheme = useCallback((nextTheme: ThemeMode) => setThemeState(nextTheme), [])
  const toggleTheme = useCallback(() => setThemeState((c) => c === 'dark' ? 'light' : 'dark'), [])
  const t = useCallback((key: TranslationKey, vars?: TranslateVars): string => translate(locale, key, vars), [locale])

  const value = useMemo(() => ({ locale, theme, setLocale, setTheme, toggleTheme, t }), [locale, theme, setLocale, setTheme, toggleTheme, t])

  return (
    <PreferencesContext.Provider value={value}>
      {children}
    </PreferencesContext.Provider>
  )
}

export function usePreferences(): PreferencesContextValue {
  const context = useContext(PreferencesContext)
  if (!context) {
    throw new Error('usePreferences must be used inside PreferencesProvider')
  }
  return context
}

function translate(locale: Locale, key: TranslationKey, vars?: TranslateVars): string {
  const template = (locale === 'en-US' ? EN : ZH)[key] || ZH[key]
  if (!vars) return template
  return template.replace(/\{(\w+)\}/g, (match, name) => {
    const value = vars[name]
    return value == null ? match : String(value)
  })
}

function readLocale(): Locale {
  const saved = window.localStorage.getItem(LOCALE_STORAGE_KEY)
  return saved === 'en-US' || saved === 'zh-CN' ? saved : 'zh-CN'
}

function readTheme(): ThemeMode {
  const saved = window.localStorage.getItem(THEME_STORAGE_KEY)
  if (saved === 'light' || saved === 'dark') return saved
  return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'
}
