# Database Table Names
TABLE_USER_SETTINGS = "user_settings"
TABLE_FACTOR_IC_DAILY = "factor_ic_daily"
TABLE_MARKET_SIGNAL_DAILY = "market_signal_daily"
TABLE_RECOMMENDATION_TRACKING = "recommendation_tracking"
TABLE_RECOMMENDATION_TRACKING_US = "recommendation_tracking_us"
TABLE_RECOMMENDATION_TRACKING_HK = "recommendation_tracking_hk"
TABLE_SIGNAL_PENDING = "signal_pending"
TABLE_PORTFOLIOS = "portfolios"
TABLE_PORTFOLIO_POSITIONS = "portfolio_positions"
TABLE_TRADE_ORDERS = "trade_orders"
TABLE_DAILY_NAV = "daily_nav"
TABLE_CONCEPT_HEAT_HISTORY = "concept_heat_history"
TABLE_SIGNAL_OBSERVATIONS = "signal_observations"
TABLE_SIGNAL_OUTCOMES = "signal_outcomes"
TABLE_SIGNAL_HEALTH_DAILY = "signal_health_daily"
TABLE_SIGNAL_REGISTRY = "signal_registry"
TABLE_SIGNAL_POLICY_SHADOW_RUNS = "signal_policy_shadow_runs"
TABLE_STRATEGY_REFLECTIONS = "strategy_reflections"
TABLE_STRATEGY_POLICY_CANDIDATES = "strategy_policy_candidates"
TABLE_STRATEGY_ATTRIBUTION_REPORTS = "strategy_attribution_reports"
TABLE_THEME_RADAR_SNAPSHOT = "theme_radar_snapshot"
TABLE_EXTERNAL_SEED_OBSERVATIONS = "external_seed_observations"
TABLE_SHADOW_ACCOUNT = "shadow_account"
TABLE_SHADOW_POSITIONS = "shadow_positions"
TABLE_SHADOW_EVENTS = "shadow_events"
TABLE_SHADOW_NAV_DAILY = "shadow_nav_daily"
TABLE_SHADOW_TRADE_PLANS = "shadow_trade_plans"
TABLE_REVIEW_SHADOW_LANE_DAILY = "review_shadow_lane_daily"
TABLE_REVIEW_CAPTURE_DAILY = "review_capture_daily"

# Local SQLite DB path
from pathlib import Path as _Path

LOCAL_DB_PATH = _Path.home() / ".wyckoff" / "wyckoff.db"
